import Foundation
import Crypto
let repo=URL(fileURLWithPath:FileManager.default.currentDirectoryPath),kit=repo.appendingPathComponent("conformance-kit")
func load(_ n:String)throws->[String:Any]{let d=try Data(contentsOf:kit.appendingPathComponent(n));return try JSONSerialization.jsonObject(with:d) as! [String:Any]}
func o(_ v:Any?)->[String:Any]{v as? [String:Any] ?? [:]};func s(_ v:Any?)->String{v as? String ?? ""};func n(_ v:Any?)->Int64{(v as? NSNumber)?.int64Value ?? -1}
func sha(_ t:String)->String{SHA256.hash(data:t.data(using:.utf8)!).map{String(format:"%02x",$0)}.joined()}
func canon(_ x:[String:Any])->String{let p=o(x["primitives"]),m=o(x["market"]),d=o(x["declared"]);let ev=(p["events"] as! [[String:Any]]).map{s($0["type"])}.joined(separator:",");return [s(x["version"]),s(o(p["entity"])["id"]),s(o(p["authority"])["id"]),s(o(p["right"])["id"]),s(m["instrument_id"]),s(m["venue_id"]),s(m["seller_entity_id"]),s(m["buyer_entity_id"]),String(n(m["quantity"])),String(n(m["unit_price_minor"])),String(n(m["originator_bps"])),s(m["usage_action"]),String(n(d["gross_minor"])),String(n(d["originator_minor"])),String(n(d["seller_net_minor"])),ev].joined(separator:"|")}
func valid(_ x:[String:Any])->Bool{if s(x["schema"]) != "entity-v3-polyglot-transaction-v1" || s(x["version"]) != "3.0.0"{return false};let p=o(x["primitives"]),m=o(x["market"]),d=o(x["declared"]),a=o(p["authority"]),r=o(p["right"]),e=o(p["entity"]);if s(a["principal_entity_id"]) != s(m["seller_entity_id"]) || s(r["grantor_entity_id"]) != s(m["seller_entity_id"]) || s(r["subject_entity_id"]) != s(e["id"]){return false};let q=n(m["quantity"]),pr=n(m["unit_price_minor"]),bps=n(m["originator_bps"]);if q<=0 || pr<0 || bps<0 || bps>10000 || s(m["buyer_entity_id"])==s(m["seller_entity_id"]){return false};if !(r["actions"] as! [String]).contains(s(m["usage_action"])){return false};let ex=["REGISTER","DELEGATE","GRANT_RIGHT","LIST","TRADE","SETTLE","ENTITLE","USE","VALUE"],ev=p["events"] as! [[String:Any]];if ev.count != ex.count{return false};for i in 0..<ex.count{if s(ev[i]["type"]) != ex[i] || n(ev[i]["seq"]) != Int64(i+1){return false}};let g=q*pr,org=g*bps/10000;if n(d["gross_minor"]) != g || n(d["originator_minor"]) != org || n(d["seller_net_minor"]) != g-org{return false};return sha(canon(x))==s(x["state_root_sha256"])}
let good=try load("VALID_TRANSACTION.json"),man=try load("CONFORMANCE_MANIFEST.json"),rec=try load("RECOVERY_EXPORT.json"),exp=try load("EXPECTED_RESULT.json");let inv=man["invalid_vectors"] as! [String];var rej=0;for f in inv{if !valid(try load(f)){rej += 1}};let controllers=(rec["controller_entities"] as! [String]).joined(separator:",");let rr=sha([s(rec["version"]),s(rec["state_root_sha256"]),controllers,String(n(rec["recovery_epoch"]))].joined(separator:"|"));let result=sha([s(good["state_root_sha256"]),s(rec["recovery_root_sha256"]),String(rej)].joined(separator:"|"));let pass=valid(good) && rr==s(rec["recovery_root_sha256"]) && s(rec["state_root_sha256"])==s(good["state_root_sha256"]) && rej==inv.count && result==s(exp["result_sha256"]);let out:[String:Any]=["implementation":"swift","pass":pass,"state_root_sha256":s(good["state_root_sha256"]),"recovery_root_sha256":s(rec["recovery_root_sha256"]),"invalid_vectors_rejected":rej,"result_sha256":result];let q=repo.appendingPathComponent("qualification");try FileManager.default.createDirectory(at:q,withIntermediateDirectories:true);let raw=try JSONSerialization.data(withJSONObject:out,options:[.prettyPrinted,.sortedKeys]);try raw.write(to:q.appendingPathComponent("result.json"));print(String(data:raw,encoding:.utf8)!);if !pass{exit(2)}

